# Generated by Django 4.1.6 on 2023-02-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MeterCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meter_id", models.CharField(blank=True, max_length=20)),
                ("gas_level", models.CharField(blank=True, max_length=10)),
                ("message_status", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
